# -*- coding: utf-8 -*-
"""Clustering_Final

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17gY9wX9foN0I1WEny4Xrwnr64VYR-B69
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.datasets.samples_generator import make_blobs
from sklearn.cluster import KMeans
# %matplotlib inline
from mpl_toolkits.mplot3d import Axes3D

from pandas import DataFrame
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

store_data = pd.read_csv('/content/compu_04.csv')

print(store_data.corr(method='pearson'))

print(store_data.columns)

x = np.array(store_data[['ESTRUCTURAS DE DATOS AVANZADAS','ECUACIONES DIFERENCIALES']])

kmeans = KMeans(n_clusters=3)
kmeans.fit(x)
centroids = kmeans.cluster_centers_
print(centroids)
#print(kmeans.predict(store_data))

labels = kmeans.predict(x)
# Getting the cluster centers
C = kmeans.cluster_centers_
colores=['red','green','blue']
asignar=[]
for row in labels:
  asignar.append(colores[row])

plt.scatter(x[:,0], x[:,1], c= asignar, s=10, alpha=0.9)
plt.scatter(centroids[:, 0], centroids[:, 1], marker='*', c=colores, s=100)
plt.xlabel('Estructuras de Datos Avanzadas')
plt.ylabel('Ecuaciones Diferenciales')
plt.show()

store_data.head()

X, y = make_blobs(n_samples=761, centers=4, cluster_std=0.60, random_state=0)
plt.scatter(X[:,0], X[:,1])